### ISSUE TITLE
Dependencies with inline dictionaries seem to be ignored

### ISSUE THREAD

**Issue by gkoz** [dhuseby/cargo-bootstrap#1]
Cargo build fails because of missing `tar` crate which doesn't get downloaded along with the others.

There're no
`cargo: Looking up info for tar`
or
`cargo: Looking up info for git2`
lines, but `git2` gets pulled in because of `git2-curl`.

It might have something to do with this syntax: https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L27

**Comment by dhuseby** [comment]
Fixed in: 8ae338c
