### ISSUE TITLE
Build scripts expect to be run in their respective crate directories

### ISSUE THREAD

**Issue by gkoz** [dhuseby/cargo-bootstrap#2]
If for some reason (missing libs or pkg-config) a sys crate build script decides to build its library from source, it fails to run `configure` because of assuming ([example](https://github.com/carllerche/curl-rust/blob/master/curl-sys/build.rs#L43)) that the current directory is the one where `build.rs` is located but `bootstrap.py` doesn't seem to `chdir` there before running the script.

**Comment by dhuseby** [comment]
Fixed in: 8ae338c
