### ISSUE TITLE
Can't bootstrap on FreeBSD 10.1

### ISSUE THREAD

**Issue by andoriyu** [dhuseby/cargo-bootstrap#4]
Running like this: `./bootstrap.py --crate-index /tmp/index --target-dir /tmp/out --no-clone  --target x86_64-unknown-freebsd`

Rust: `rustc 1.0.0-dev (built 2015-06-12)`

``````
cargo:threadpool: Building threadpool-0.1.4 (needed by: cargo-0.3.0)
cargo:threadpool: rustc /tmp/out/threadpool-0.1.4/src/lib.rs --crate-name threadpool --crate-type lib -C extra-filename=-0_1_4 --out-dir /tmp/out -L /tmp/out

cargo:filetime: Building filetime-0.1.4 (needed by: cargo-0.3.0)
cargo:filetime: rustc /tmp/out/filetime-0.1.4/src/lib.rs --crate-name filetime --crate-type lib -C extra-filename=-0_1_4 --out-dir /tmp/out -L /tmp/out
/tmp/out/filetime-0.1.4/src/lib.rs:110:29: 110:57 error: unresolved import `std::os::freebsd::fs::MetadataExt`. Could not find `freebsd` in `std::os`
/tmp/out/filetime-0.1.4/src/lib.rs:110                         use std::os::$i::fs::MetadataExt;
                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/out/filetime-0.1.4/src/lib.rs:104:9: 123:10 note: in expansion of birthtim!
/tmp/out/filetime-0.1.4/src/lib.rs:125:9: 131:10 note: expansion site
error: aborting due to previous error

Exception:
 from ./bootstrap.py, line 897:
 build command failed: 101```
``````

**Comment by dhuseby** [comment]
So I think rust on FreeBSD is currently broken.  I'll ask around today and see if that is correct.

**Comment by andoriyu** [comment]
@dhuseby port version of rustc works with compiled cargo.

**Comment by dhuseby** [comment]
alright, let me give it a try then.

**Comment by dhuseby** [comment]
oh wait, that won't compile because it's dependent on newer rust stdlib that what is in the port package.  so i need to get freebsd rust building from source again.  currently it is broken.

**Comment by andoriyu** [comment]
oh, I see.

**Comment by dhuseby** [comment]
This is almost resolved.  Hang in there!

**Comment by dhuseby** [comment]
FreeBSD Rust is building again: http://buildbot.rust-lang.org/builders/auto-freebsd10_64-1

I tried this script out on a fresh install of FreeBSD 10.1 x86_64.  It worked all but the final link command.  I had to add `-L native=/usr/local/lib` to the final command and it worked.  Let me figure out why that wasn't being carried through to the final command and fix the script.  If you're impatient, you can just do that for now.
